function visualize_mitlangloc_ifg_lang_responses()
% VISUALIZE_MITLANGLOC_IFG_LANG_RESPONSES  IFG lang electrodes (MGH MITLangloc).
%
%   Run:
%     visualize_mitlangloc_ifg_lang_responses

repoRoot   = fileparts(fileparts(mfilename('fullpath')));
workingDir = 'F:\seeg\luohong\analysisEV';
crunchedDir = fullfile(workingDir, 'crunched', 'MITLangloc');
signalType = 'bipolar';

run_ifg_lang_response_analysis( ...
    'analysisTitle', 'MITLANGLOC IFG LANGUAGE RESPONSES', ...
    'mniPlotTitle', 'MITLangloc IFG lang electrodes', ...
    'taskType', 'MITLangloc', ...
    'cohortName', 'MGH', ...
    'crunchedDir', crunchedDir, ...
    'cohortKind', 'broadband', ...
    'subjects', {}, ...
    'outputDir', fullfile(workingDir, 'output', 'MITLangloc', ...
        sprintf('ifg_lang_responses_%s', lower(signalType))), ...
    'repoRoot', repoRoot, ...
    'signalType', signalType, ...
    'auxSearchDirs', {workingDir, crunchedDir, 'F:\iEEG_evlab'});
end
