function visualize_mitswjntask_ifg_lang_responses()
% VISUALIZE_MITSWJNTASK_IFG_LANG_RESPONSES  IFG lang electrodes (local LangLoc).
%
%   Extracts language-responsive IFG channels from your Brainstorm pipeline
%   MITSWJNTask LangLoc results (Subject_##_MITSWJNTask_crunched.mat).
%
%   Run:
%     visualize_mitswjntask_ifg_lang_responses

repoRoot   = fileparts(fileparts(mfilename('fullpath')));
workingDir = 'F:\seeg\luohong\analysisEV';
taskType   = 'MITSWJNTask';
signalType = 'bipolar';

% Leave {} to auto-detect all subjects with finished analysis in workingDir
localSubjects = {};

run_ifg_lang_response_analysis( ...
    'analysisTitle', 'MITSWJNTASK IFG LANGUAGE RESPONSES', ...
    'mniPlotTitle', 'MITSWJNTask IFG lang electrodes', ...
    'taskType', taskType, ...
    'cohortName', 'local', ...
    'crunchedDir', workingDir, ...
    'cohortKind', 'brainstorm', ...
    'subjects', localSubjects, ...
    'outputDir', fullfile(workingDir, 'output', taskType, ...
        sprintf('ifg_lang_responses_%s', lower(signalType))), ...
    'repoRoot', repoRoot, ...
    'signalType', signalType, ...
    'auxSearchDirs', {workingDir, fullfile(workingDir, 'crunched', 'MITLangloc'), 'F:\iEEG_evlab'});
end
