function obj = wrap_crunched_obj_as_seeg(src)
% WRAP_CRUNCHED_OBJ_AS_SEEG  Wrap a merged-pipeline obj as ecog_data_seeg.
%
%   obj = wrap_crunched_obj_as_seeg(src)
%
%   Accepts objects from the ieeg_pipeline engine (ecog_data / ecog_data_ieeg)
%   or an existing ecog_data_seeg and returns ecog_data_seeg with all fields
%   copied. Use when loading external crunched files such as
%   <subject>_MITLangloc_crunched_defaultSEEGorBOTHBroadBand.mat.

if isa(src, 'ecog_data_seeg')
    obj = src;
    return;
end

if ~isa(src, 'ecog_data_ieeg') && ~strcmp(class(src), 'ecog_data')
    error('Expected ecog_data, ecog_data_ieeg, or ecog_data_seeg; got %s', class(src));
end

obj = ecog_data_seeg(...
    src.for_preproc, ...
    src.subject, ...
    src.experiment, ...
    src.crunched_file_name, ...
    src.crunched_file_path, ...
    src.raw_file_name, ...
    src.raw_file_path, ...
    src.elec_ch_label, ...
    src.elec_ch, ...
    src.elec_ch_prelim_deselect, ...
    src.elec_ch_type ...
);

skipProps = {'for_preproc', 'subject', 'experiment', ...
    'crunched_file_name', 'crunched_file_path', ...
    'raw_file_name', 'raw_file_path', ...
    'elec_ch_label', 'elec_ch', 'elec_ch_prelim_deselect', 'elec_ch_type'};

props = properties(src);
for i = 1:numel(props)
    pname = props{i};
    if ismember(pname, skipProps) || ~isprop(obj, pname)
        continue;
    end
    obj.(pname) = src.(pname);
end
end
